TYPE_PRONAJEM_ID = "a-type-pronajem"
TYPE_BYT_ID = "a-type-byt"
LOCATION_INPUT_ID = "locationInput"
PRICE_FROM_ID = "priceFrom"
PRICE_TO_ID = "priceTo"
TYPE_OF_HOUSING_XPATH = "//*[@id='bzr-multiselect-estateType']/a"
SELECT_DUM_XPATH = "//*[@id='bzr-multiselect-estateType']/div/span[2]/label/span[2]"
TYPE_OF_DISPOSITION_XPATH = "//*[@id='bzr-multiselect-disposition']/a"
ADDITIONAL_PARAMETERS_XPATH = "//*[@id='search-content']/form/div[2]/div[2]/div[3]/div[1]/p/a/span[3]"
SURFACE_FROM_ID = "surfaceFrom"
SEARCH_BUTTON_XPATH = "//*[@id='search-content']/form/div[2]/div[2]/div[3]/div[2]/p/button"
ACCEPT_COOKIES_ID = "onetrust-accept-btn-handler"
CLOSE_ADVERTISEMENT_XPATH = "/html/body/div[11]/div/div/div[2]/div/a/img"

